version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_REPLICA_SET_NAME: replicaSet1
    networks:
      - mongo_network
    command: --replSet "replicaSet1"

volumes:
  mongo-data:

networks:
  mongo_network:
    driver: bridge